# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_method', models.CharField(choices=[('reception', 'Reception'), ('mobile', 'Mobile'), ('qr_code', 'QR Code'), ('self_service', 'Self Service')], max_length=20)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_checkins', to='scheduling.appointment')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_patients', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_checkins', to='facilities.facility')),
                ('facility_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_checkins', to='facilities.facilityspecialty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='patients.patient')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_patient_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_checkins',
            },
        ),
        migrations.CreateModel(
            name='CheckinToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Hash values must be 64 hexadecimal characters.', regex='^[0-9A-Fa-f]{64}$')])),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkin_tokens', to='scheduling.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checkin_tokens', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_checkin_tokens', to=settings.AUTH_USER_MODEL)),
                ('patient_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkin_tokens', to='checkins.patientcheckin')),
            ],
            options={
                'db_table': 'checkin_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='patientcheckin',
            index=models.Index(fields=['facility', 'checked_in_at'], name='idx_pat_checkin_fac_time'),
        ),
        migrations.AddIndex(
            model_name='patientcheckin',
            index=models.Index(fields=['patient', 'checked_in_at'], name='idx_pat_checkin_pat_time'),
        ),
        migrations.AddIndex(
            model_name='patientcheckin',
            index=models.Index(fields=['facility_specialty'], name='idx_patient_checkins_specialty'),
        ),
        migrations.AddConstraint(
            model_name='patientcheckin',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False), ('voided_at__isnull', True)), fields=('appointment',), name='uq_patient_checkins_active_appointment'),
        ),
        migrations.AddConstraint(
            model_name='patientcheckin',
            constraint=models.CheckConstraint(condition=models.Q(('checkin_method__in', ['reception', 'mobile', 'qr_code', 'self_service'])), name='ck_patient_checkins_method'),
        ),
        migrations.AddConstraint(
            model_name='patientcheckin',
            constraint=models.CheckConstraint(condition=models.Q(('appointment__isnull', False), ('facility_specialty__isnull', False), _connector='OR'), name='ck_patient_checkins_walkin_specialty'),
        ),
        migrations.AddConstraint(
            model_name='patientcheckin',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('voided_at__isnull', True), ('voided_by__isnull', True), ('void_reason__isnull', True)), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), ('void_reason__isnull', False), ('voided_at__gte', models.F('checked_in_at'))), _connector='OR'), name='ck_patient_checkins_void'),
        ),
        migrations.AddIndex(
            model_name='checkintoken',
            index=models.Index(fields=['appointment'], name='idx_checkin_tokens_appointment'),
        ),
        migrations.AddIndex(
            model_name='checkintoken',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True), ('used_at__isnull', True)), fields=['expires_at'], name='idx_checkin_tokens_expiry'),
        ),
        migrations.AddConstraint(
            model_name='checkintoken',
            constraint=models.UniqueConstraint(fields=('token_hash',), name='uq_checkin_tokens_hash'),
        ),
        migrations.AddConstraint(
            model_name='checkintoken',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('used_at__isnull', True)), fields=('appointment',), name='uq_checkin_tokens_active_appointment'),
        ),
        migrations.AddConstraint(
            model_name='checkintoken',
            constraint=models.UniqueConstraint(condition=models.Q(('patient_checkin__isnull', False)), fields=('patient_checkin',), name='uq_checkin_tokens_checkin'),
        ),
        migrations.AddConstraint(
            model_name='checkintoken',
            constraint=models.CheckConstraint(condition=models.Q(('token_hash__regex', '^[0-9A-Fa-f]{64}$')), name='ck_checkin_tokens_hash'),
        ),
        migrations.AddConstraint(
            model_name='checkintoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='ck_checkin_tokens_expiry'),
        ),
    ]
