# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, for example +2557656765456.', regex='^\\+[1-9][0-9]{7,14}$')])),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_departments', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='facilities.facility')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('location_description', models.CharField(blank=True, max_length=250, null=True)),
                ('floor', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity', models.SmallIntegerField(default=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_rooms', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_rooms', to='facilities.facility')),
            ],
            options={
                'db_table': 'consultation_rooms',
            },
        ),
        migrations.CreateModel(
            name='FacilityFlowSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_advance_booking_days', models.SmallIntegerField(default=30)),
                ('minimum_booking_notice_minutes', models.IntegerField(default=0)),
                ('cancellation_cutoff_minutes', models.IntegerField(default=60)),
                ('reschedule_cutoff_minutes', models.IntegerField(default=60)),
                ('early_checkin_minutes', models.IntegerField(default=30)),
                ('late_checkin_grace_minutes', models.IntegerField(default=15)),
                ('no_show_after_minutes', models.IntegerField(default=15)),
                ('default_reminder_minutes_before', models.IntegerField(blank=True, default=1440, null=True)),
                ('queue_number_padding', models.SmallIntegerField(default=3)),
                ('auto_create_daily_queues', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_facility_flow_settings', to=settings.AUTH_USER_MODEL)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_settings', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_flow_settings',
            },
        ),
        migrations.CreateModel(
            name='FacilityOperatingHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.SmallIntegerField()),
                ('period_order', models.SmallIntegerField(default=1)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('closes_next_day', models.BooleanField(default=False)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_operating_hours',
            },
        ),
        migrations.CreateModel(
            name='FacilityScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exception_date', models.DateField()),
                ('period_order', models.SmallIntegerField(default=1)),
                ('is_closed', models.BooleanField(default=False)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('closes_next_day', models.BooleanField(default=False)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_schedule_exceptions',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facility_types',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_facility_types_name'), models.UniqueConstraint(fields=('code',), name='uq_facility_types_code'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_facility_types_code_upper')],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.facilitytype'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, for example +2557656765456.', regex='^\\+[1-9][0-9]{7,14}$')])),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='idx_organizations_code')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uq_organizations_code'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_organizations_code_upper')],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.organization'),
        ),
        migrations.CreateModel(
            name='ServicePointType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_point_types',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_service_point_types_name'), models.UniqueConstraint(fields=('code',), name='uq_service_point_types_code'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_service_point_types_code_upper')],
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('location_description', models.CharField(blank=True, max_length=250, null=True)),
                ('floor', models.CharField(blank=True, max_length=30, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_points', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_points', to='facilities.facility')),
                ('service_point_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_points', to='facilities.servicepointtype')),
            ],
            options={
                'db_table': 'service_points',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_specialties', to='facilities.specialty')),
            ],
            options={
                'db_table': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='FacilitySpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_duration_minutes', models.SmallIntegerField()),
                ('accepts_appointments', models.BooleanField(default=True)),
                ('accepts_walk_ins', models.BooleanField(default=False)),
                ('requires_referral', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_specialties', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_specialties', to='facilities.facility')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_specialties', to='facilities.specialty')),
            ],
            options={
                'db_table': 'facility_specialties',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['facility'], name='idx_departments_facility'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='uq_departments_facility_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_departments_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('parent_department__isnull', True), models.Q(('parent_department', models.F('id')), _negated=True), _connector='OR'), name='ck_departments_no_self_parent'),
        ),
        migrations.AddIndex(
            model_name='consultationroom',
            index=models.Index(fields=['facility'], name='idx_consult_room_fac'),
        ),
        migrations.AddConstraint(
            model_name='consultationroom',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='uq_consultation_rooms_facility_code'),
        ),
        migrations.AddConstraint(
            model_name='consultationroom',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_consultation_rooms_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='consultationroom',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='ck_consultation_rooms_capacity'),
        ),
        migrations.AddConstraint(
            model_name='facilityflowsetting',
            constraint=models.CheckConstraint(condition=models.Q(('max_advance_booking_days__gte', 0), ('minimum_booking_notice_minutes__gte', 0), ('cancellation_cutoff_minutes__gte', 0), ('reschedule_cutoff_minutes__gte', 0), ('early_checkin_minutes__gte', 0), ('late_checkin_grace_minutes__gte', 0), ('no_show_after_minutes__gte', 0), models.Q(('default_reminder_minutes_before__isnull', True), ('default_reminder_minutes_before__gte', 0), _connector='OR')), name='ck_facility_flow_settings_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='facilityflowsetting',
            constraint=models.CheckConstraint(condition=models.Q(('queue_number_padding__gte', 1), ('queue_number_padding__lte', 6)), name='ck_facility_flow_settings_padding'),
        ),
        migrations.AddIndex(
            model_name='facilityoperatinghour',
            index=models.Index(fields=['facility', 'day_of_week', 'is_active'], name='idx_fac_op_hour_lookup'),
        ),
        migrations.AddConstraint(
            model_name='facilityoperatinghour',
            constraint=models.UniqueConstraint(fields=('facility', 'day_of_week', 'period_order'), name='uq_facility_operating_hours_period'),
        ),
        migrations.AddConstraint(
            model_name='facilityoperatinghour',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='ck_facility_operating_hours_day'),
        ),
        migrations.AddConstraint(
            model_name='facilityoperatinghour',
            constraint=models.CheckConstraint(condition=models.Q(('period_order__gt', 0)), name='ck_facility_operating_hours_period_order'),
        ),
        migrations.AddConstraint(
            model_name='facilityoperatinghour',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_24_hours', True), ('opens_at__isnull', True), ('closes_at__isnull', True), ('closes_next_day', False)), models.Q(('is_24_hours', False), ('opens_at__isnull', False), ('closes_at__isnull', False), models.Q(('opens_at', models.F('closes_at')), _negated=True), models.Q(('closes_next_day', True), ('closes_at__gt', models.F('opens_at')), _connector='OR')), _connector='OR'), name='ck_facility_operating_hours_shape'),
        ),
        migrations.AddIndex(
            model_name='facilityscheduleexception',
            index=models.Index(fields=['facility', 'exception_date', 'is_active'], name='idx_fac_sched_exc_lookup'),
        ),
        migrations.AddConstraint(
            model_name='facilityscheduleexception',
            constraint=models.UniqueConstraint(fields=('facility', 'exception_date', 'period_order'), name='uq_facility_schedule_exceptions_period'),
        ),
        migrations.AddConstraint(
            model_name='facilityscheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(('period_order__gt', 0)), name='ck_facility_schedule_exceptions_period_order'),
        ),
        migrations.AddConstraint(
            model_name='facilityscheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_closed', True), ('is_24_hours', False), ('opens_at__isnull', True), ('closes_at__isnull', True), ('closes_next_day', False)), models.Q(('is_closed', False), ('is_24_hours', True), ('opens_at__isnull', True), ('closes_at__isnull', True), ('closes_next_day', False)), models.Q(('is_closed', False), ('is_24_hours', False), ('opens_at__isnull', False), ('closes_at__isnull', False), models.Q(('opens_at', models.F('closes_at')), _negated=True), models.Q(('closes_next_day', True), ('closes_at__gt', models.F('opens_at')), _connector='OR')), _connector='OR'), name='ck_facility_schedule_exceptions_shape'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['organization'], name='idx_facilities_organization'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type'], name='idx_facilities_type'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['is_active'], name='idx_facilities_active'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_facilities_org_code'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_facilities_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('country_code__isnull', True), ('country_code', django.db.models.functions.text.Upper('country_code')), _connector='OR'), name='ck_facilities_country_upper'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='ck_facilities_coordinates_pair'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='ck_facilities_latitude'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='ck_facilities_longitude'),
        ),
        migrations.AddIndex(
            model_name='servicepoint',
            index=models.Index(fields=['facility'], name='idx_service_points_facility'),
        ),
        migrations.AddConstraint(
            model_name='servicepoint',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='uq_service_points_facility_code'),
        ),
        migrations.AddConstraint(
            model_name='servicepoint',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_service_points_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='servicepoint',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='ck_service_points_display_order'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_specialties_name'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_specialties_code'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_specialties_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.CheckConstraint(condition=models.Q(('parent_specialty__isnull', True), models.Q(('parent_specialty', models.F('id')), _negated=True), _connector='OR'), name='ck_specialties_no_self_parent'),
        ),
        migrations.AddIndex(
            model_name='facilityspecialty',
            index=models.Index(fields=['facility'], name='idx_fac_spec_fac'),
        ),
        migrations.AddIndex(
            model_name='facilityspecialty',
            index=models.Index(fields=['specialty'], name='idx_fac_spec_spec'),
        ),
        migrations.AddIndex(
            model_name='facilityspecialty',
            index=models.Index(fields=['department'], name='idx_fac_spec_dept'),
        ),
        migrations.AddConstraint(
            model_name='facilityspecialty',
            constraint=models.CheckConstraint(condition=models.Q(('appointment_duration_minutes__gt', 0)), name='ck_facility_specialties_duration'),
        ),
        migrations.AddConstraint(
            model_name='facilityspecialty',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('facility', 'specialty'), name='uq_facility_specialties_without_department'),
        ),
        migrations.AddConstraint(
            model_name='facilityspecialty',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('facility', 'specialty', 'department'), name='uq_facility_specialties_with_department'),
        ),
    ]
