# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='facilities.organization'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='facilities.organization'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_permissions_name'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_permissions_code'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('module', 'action'), name='uq_permissions_module_action'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Lower('code'))), name='ck_permissions_code_lower'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z0-9_]+\\.[a-z0-9_]+$')), name='ck_permissions_code_format'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('module', django.db.models.functions.text.Lower('module'))), name='ck_permissions_module_lower'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('action', django.db.models.functions.text.Lower('action'))), name='ck_permissions_action_lower'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization'], name='idx_roles_organization'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['facility'], name='idx_roles_facility'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_roles_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('facility__isnull', True)), models.Q(('organization__isnull', False), ('facility__isnull', True)), models.Q(('organization__isnull', False), ('facility__isnull', False)), _connector='OR'), name='ck_roles_scope'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('facility__isnull', True), ('organization__isnull', True)), name='uq_roles_platform_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', True), ('organization__isnull', True)), fields=('code',), name='uq_roles_platform_code'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), condition=models.Q(('facility__isnull', True), ('organization__isnull', False)), name='uq_roles_org_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', True), ('organization__isnull', False)), fields=('organization', 'code'), name='uq_roles_org_code'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('facility'), condition=models.Q(('facility__isnull', False)), name='uq_roles_facility_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('facility', 'code'), name='uq_roles_facility_code'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='idx_role_perm_role_act'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='idx_role_perm_perm'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permissions_pair'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user', 'is_active'], name='idx_user_memb_user_act'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['organization'], name='idx_user_memberships_org'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['facility'], name='idx_user_memberships_facility'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='ck_user_memberships_dates'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', True)), fields=('user', 'organization'), name='uq_user_memberships_org'),
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('user', 'facility'), name='uq_user_memberships_facility'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'is_active'], name='idx_user_role_asn_user_act'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['role'], name='idx_user_role_assignments_role'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uq_user_role_assignments_pair'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='ck_user_role_assignments_dates'),
        ),
    ]
