# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(max_length=50)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('pdf', 'PDF')], max_length=10)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to='facilities.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to='facilities.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_exports',
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='idx_report_exp_req_time'), models.Index(fields=['organization', 'status', '-created_at'], name='idx_report_exports_org_status'), models.Index(fields=['facility'], name='idx_report_exports_facility')],
                'constraints': [models.CheckConstraint(condition=models.Q(('export_format__in', ['csv', 'xlsx', 'pdf'])), name='ck_report_exports_format'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed', 'failed', 'expired', 'cancelled'])), name='ck_report_exports_status'), models.CheckConstraint(condition=models.Q(('row_count__isnull', True), ('row_count__gte', 0), _connector='OR'), name='ck_report_exports_row_count'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), models.Q(('storage_key__isnull', False), ('generated_at__isnull', False)), _connector='OR'), name='ck_report_exports_completion'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), models.Q(('failed_at__isnull', False), ('failure_reason__isnull', False)), _connector='OR'), name='ck_report_exports_failure'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), models.Q(('generated_at__isnull', False), ('expires_at__gt', models.F('generated_at'))), _connector='OR'), name='ck_report_exports_expiry')],
            },
        ),
    ]
