# Generated by Django 5.2.4 on 2026-09-09 19:23

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('facilities', '0002_postgres_hardening'),
        ('patients', '0002_patientallergy_patientcondition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_type', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab'), ('imaging', 'Imaging'), ('procedure', 'Procedure'), ('pharmacy', 'Pharmacy'), ('bed', 'Bed'), ('manual', 'Manual')], max_length=30)),
                ('source_reference_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('voided', 'Voided')], default='pending', max_length=30)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encounter_charges', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='clinical.encounter')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_encounter_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encounter_charges',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinical.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=30)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payment_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_refunds',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_category', models.CharField(choices=[('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('procedure', 'Procedure'), ('pharmacy', 'Pharmacy'), ('admission', 'Admission'), ('bed', 'Bed'), ('other', 'Other')], max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_services', to='facilities.organization')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('encounter_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.encountercharge')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.invoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.service')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
        migrations.AddField(
            model_name='encountercharge',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_charges', to='billing.service'),
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_prices', to='facilities.facility')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='billing.service')),
            ],
            options={
                'db_table': 'service_prices',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'issued_at'], name='idx_invoices_patient_time'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['facility', 'status', 'issued_at'], name='idx_invoices_fac_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('facility', 'invoice_number'), name='uq_invoices_facility_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'issued', 'partially_paid', 'paid', 'cancelled'])), name='ck_invoices_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('discount_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gte', 0), ('paid_amount__gte', 0), ('balance_amount__gte', 0)), name='ck_invoices_money'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount_amount')), '+', models.F('tax_amount'))), ('balance_amount', django.db.models.expressions.CombinedExpression(models.F('total_amount'), '-', models.F('paid_amount')))), name='ck_invoices_totals'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('issued_at__isnull', False), _connector='OR'), name='ck_invoices_issued'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__isnull', True), ('issued_at__isnull', True), ('due_at__gte', models.F('issued_at')), _connector='OR'), name='ck_invoices_due'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', 'received_at'], name='idx_payments_patient_time'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('facility', 'payment_number'), name='uq_payments_facility_number'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payments_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('currency', django.db.models.functions.text.Upper('currency'))), name='ck_payments_currency_upper'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['cash', 'mobile_money', 'card', 'bank', 'insurance', 'other'])), name='ck_payments_method'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'completed', 'failed', 'reversed'])), name='ck_payments_status'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment'], name='idx_payment_refunds_payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_refunds_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'completed', 'cancelled'])), name='ck_payment_refunds_status'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('refunded_at__isnull', False), _connector='OR'), name='ck_payment_refunds_completion'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['organization', 'service_category', 'is_active'], name='idx_services_org_category'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_services_org_code'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_services_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('service_category__in', ['consultation', 'laboratory', 'imaging', 'procedure', 'pharmacy', 'admission', 'bed', 'other'])), name='ck_services_category'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='idx_invoice_items_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('discount_amount__gte', 0), ('tax_amount__gte', 0), ('line_total__gte', 0)), name='ck_invoice_items_money'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), 2), '-', models.F('discount_amount')), '+', models.F('tax_amount')))), name='ck_invoice_items_total'),
        ),
        migrations.AddIndex(
            model_name='encountercharge',
            index=models.Index(fields=['encounter', 'status'], name='idx_enc_charges_enc_status'),
        ),
        migrations.AddIndex(
            model_name='encountercharge',
            index=models.Index(condition=models.Q(('source_reference_id__isnull', False)), fields=['source_type', 'source_reference_id'], name='idx_enc_charges_source_lookup'),
        ),
        migrations.AddConstraint(
            model_name='encountercharge',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('amount__gte', 0)), name='ck_encounter_charges_money'),
        ),
        migrations.AddConstraint(
            model_name='encountercharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), 2))), name='ck_encounter_charges_amount'),
        ),
        migrations.AddConstraint(
            model_name='encountercharge',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['consultation', 'lab', 'imaging', 'procedure', 'pharmacy', 'bed', 'manual'])), name='ck_encounter_charges_source'),
        ),
        migrations.AddConstraint(
            model_name='encountercharge',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'posted', 'voided'])), name='ck_encounter_charges_status'),
        ),
        migrations.AddConstraint(
            model_name='encountercharge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'voided'), _negated=True), ('voided_at__isnull', True), ('voided_by__isnull', True), ('void_reason__isnull', True)), models.Q(('status', 'voided'), ('voided_at__isnull', False), ('void_reason__isnull', False)), _connector='OR'), name='ck_encounter_charges_void'),
        ),
        migrations.AddConstraint(
            model_name='encountercharge',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference_id__isnull', False), models.Q(('status', 'voided'), _negated=True)), fields=('encounter', 'service', 'source_type', 'source_reference_id'), name='uq_encounter_charges_source'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['service', 'effective_from', 'effective_to'], name='idx_service_prices_dates'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_service_prices_amount'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('currency', django.db.models.functions.text.Upper('currency'))), name='ck_service_prices_currency_upper'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_service_prices_dates'),
        ),
    ]
