# Generated by Django 5.2.4 on 2026-09-09 14:52

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('facilities', '0002_postgres_hardening'),
        ('practitioners', '0002_postgres_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'Stat')], default='routine', max_length=20)),
                ('clinical_notes_encrypted', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collection', 'Sample Collection'), ('processing', 'Processing'), ('partially_resulted', 'Partially Resulted'), ('resulted', 'Resulted'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='ordered', max_length=30)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lab_orders', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='clinical.encounter')),
                ('ordered_by_practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'lab_orders',
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collection', 'Sample Collection'), ('processing', 'Processing'), ('resulted', 'Resulted'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='ordered', max_length=30)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='laboratory.laborder')),
            ],
            options={
                'db_table': 'lab_order_items',
            },
        ),
        migrations.CreateModel(
            name='LabSpecimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specimen_number', models.CharField(max_length=80, unique=True)),
                ('specimen_type', models.CharField(max_length=80)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('received', 'Received'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('disposed', 'Disposed')], default='pending', max_length=30)),
                ('rejection_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('collected_by_practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collected_lab_specimens', to='practitioners.practitionerfacilityassignment')),
                ('lab_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='laboratory.laborderitem')),
                ('received_by_practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_lab_specimens', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'lab_specimens',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=80, null=True)),
                ('turnaround_minutes', models.IntegerField(blank=True, null=True)),
                ('billing_service_id', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='facilities.organization')),
            ],
            options={
                'db_table': 'lab_tests',
            },
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest'),
        ),
        migrations.CreateModel(
            name='LabTestComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='laboratory.labtest')),
            ],
            options={
                'db_table': 'lab_test_components',
            },
        ),
        migrations.CreateModel(
            name='LabResultValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('abnormal_flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes_encrypted', models.TextField(blank=True, null=True)),
                ('entered_by_practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_lab_results', to='practitioners.practitionerfacilityassignment')),
                ('lab_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_values', to='laboratory.laborderitem')),
                ('verified_by_practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_lab_results', to='practitioners.practitionerfacilityassignment')),
                ('lab_test_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_values', to='laboratory.labtestcomponent')),
            ],
            options={
                'db_table': 'lab_result_values',
            },
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['encounter', 'ordered_at'], name='idx_lab_orders_encounter_time'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'ordered_at'], name='idx_lab_orders_status_time'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['routine', 'urgent', 'stat'])), name='ck_lab_orders_priority'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ordered', 'sample_collection', 'processing', 'partially_resulted', 'resulted', 'verified', 'cancelled'])), name='ck_lab_orders_status'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('cancellation_reason__isnull', True)), models.Q(('status', 'cancelled'), ('cancelled_at__isnull', False), ('cancellation_reason__isnull', False)), _connector='OR'), name='ck_lab_orders_cancellation'),
        ),
        migrations.AddIndex(
            model_name='labspecimen',
            index=models.Index(fields=['specimen_number'], name='idx_lab_specimens_number'),
        ),
        migrations.AddConstraint(
            model_name='labspecimen',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'collected', 'received', 'rejected', 'processing', 'disposed'])), name='ck_lab_specimens_status'),
        ),
        migrations.AddConstraint(
            model_name='labspecimen',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'rejected'), _negated=True), ('rejection_reason__isnull', True)), models.Q(('status', 'rejected'), ('rejection_reason__isnull', False)), _connector='OR'), name='ck_lab_specimens_rejection'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['organization', 'is_active'], name='idx_lab_tests_org_active'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_lab_tests_org_code'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_lab_tests_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='labtest',
            constraint=models.CheckConstraint(condition=models.Q(('turnaround_minutes__isnull', True), ('turnaround_minutes__gt', 0), _connector='OR'), name='ck_lab_tests_turnaround'),
        ),
        migrations.AddIndex(
            model_name='laborderitem',
            index=models.Index(fields=['lab_order'], name='idx_lab_order_items_order'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.UniqueConstraint(fields=('lab_order', 'lab_test'), name='uq_lab_order_items_order_test'),
        ),
        migrations.AddConstraint(
            model_name='laborderitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ordered', 'sample_collection', 'processing', 'resulted', 'verified', 'cancelled'])), name='ck_lab_order_items_status'),
        ),
        migrations.AddIndex(
            model_name='labtestcomponent',
            index=models.Index(fields=['lab_test', 'display_order'], name='idx_lab_components_order'),
        ),
        migrations.AddConstraint(
            model_name='labtestcomponent',
            constraint=models.UniqueConstraint(fields=('lab_test', 'code'), name='uq_lab_test_components_test_code'),
        ),
        migrations.AddConstraint(
            model_name='labtestcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_lab_test_components_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='labtestcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('reference_low__isnull', True), ('reference_high__isnull', True), ('reference_high__gte', models.F('reference_low')), _connector='OR'), name='ck_lab_test_components_reference'),
        ),
        migrations.AddConstraint(
            model_name='labtestcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 0)), name='ck_lab_test_components_order'),
        ),
        migrations.AddIndex(
            model_name='labresultvalue',
            index=models.Index(fields=['lab_order_item'], name='idx_lab_result_values_item'),
        ),
        migrations.AddConstraint(
            model_name='labresultvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_numeric__isnull', False), ('value_text__isnull', True)), models.Q(('value_numeric__isnull', True), ('value_text__isnull', False)), _connector='OR'), name='ck_lab_result_values_value'),
        ),
        migrations.AddConstraint(
            model_name='labresultvalue',
            constraint=models.CheckConstraint(condition=models.Q(('reference_low__isnull', True), ('reference_high__isnull', True), ('reference_high__gte', models.F('reference_low')), _connector='OR'), name='ck_lab_result_values_reference'),
        ),
        migrations.AddConstraint(
            model_name='labresultvalue',
            constraint=models.CheckConstraint(condition=models.Q(('abnormal_flag__in', ['normal', 'low', 'high', 'critical'])), name='ck_lab_result_values_abnormal'),
        ),
        migrations.AddConstraint(
            model_name='labresultvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verified_at__isnull', True), ('verified_by_practitioner_facility_assignment__isnull', True)), models.Q(('verified_at__isnull', False), ('verified_by_practitioner_facility_assignment__isnull', False)), _connector='OR'), name='ck_lab_result_values_verification'),
        ),
    ]
