# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('practitioner_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format.', regex='^\\+[1-9][0-9]{7,14}$')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practitioners', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioners', to='facilities.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practitioners',
            },
        ),
        migrations.CreateModel(
            name='PractitionerCredentialType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('requires_expiry_date', models.BooleanField(default=False)),
                ('requires_verification', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practitioner_credential_types', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_credential_types', to='facilities.organization')),
            ],
            options={
                'db_table': 'practitioner_credential_types',
            },
        ),
        migrations.CreateModel(
            name='PractitionerCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credential_number_encrypted', models.TextField()),
                ('credential_number_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Hash values must be 64 hexadecimal characters.', regex='^[0-9A-Fa-f]{64}$')])),
                ('last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=150, null=True)),
                ('issuing_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practitioner_credentials', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='practitioners.practitioner')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_practitioner_credentials', to=settings.AUTH_USER_MODEL)),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='practitioners.practitionercredentialtype')),
            ],
            options={
                'db_table': 'practitioner_credentials',
            },
        ),
        migrations.CreateModel(
            name='PractitionerFacilityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_practitioner_facilities', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_assignments', to='facilities.facility')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_assignments', to='practitioners.practitioner')),
            ],
            options={
                'db_table': 'practitioner_facility_assignments',
            },
        ),
        migrations.CreateModel(
            name='PractitionerDepartmentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_practitioner_departments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_assignments', to='facilities.department')),
                ('practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_assignments', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'practitioner_department_assignments',
            },
        ),
        migrations.CreateModel(
            name='PractitionerSpecialtyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_practitioner_specialties', to=settings.AUTH_USER_MODEL)),
                ('facility_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_assignments', to='facilities.facilityspecialty')),
                ('practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_assignments', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'practitioner_specialty_assignments',
            },
        ),
        migrations.CreateModel(
            name='PractitionerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('requires_license', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practitioner_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practitioner_types',
            },
        ),
        migrations.AddField(
            model_name='practitioner',
            name='practitioner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioners', to='practitioners.practitionertype'),
        ),
        migrations.AddIndex(
            model_name='practitionercredentialtype',
            index=models.Index(fields=['organization'], name='idx_prac_cred_type_org'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredentialtype',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_practitioner_credential_types_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredentialtype',
            constraint=models.CheckConstraint(condition=models.Q(('country_code__isnull', True), ('country_code', django.db.models.functions.text.Upper('country_code')), _connector='OR'), name='ck_practitioner_credential_types_country_upper'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredentialtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('organization__isnull', True)), name='uq_practitioner_credential_types_global_name'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredentialtype',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='uq_practitioner_credential_types_global_code'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredentialtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), condition=models.Q(('organization__isnull', False)), name='uq_practitioner_credential_types_org_name'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredentialtype',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'code'), name='uq_practitioner_credential_types_org_code'),
        ),
        migrations.AddIndex(
            model_name='practitionercredential',
            index=models.Index(fields=['practitioner', 'is_active'], name='idx_prac_cred_prac'),
        ),
        migrations.AddIndex(
            model_name='practitionercredential',
            index=models.Index(fields=['credential_type'], name='idx_prac_cred_type'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredential',
            constraint=models.UniqueConstraint(fields=('credential_type', 'credential_number_hash'), name='uq_practitioner_credentials_type_hash'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredential',
            constraint=models.CheckConstraint(condition=models.Q(('credential_number_hash__regex', '^[0-9A-Fa-f]{64}$')), name='ck_practitioner_credentials_hash'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredential',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status__in', ['unverified', 'pending', 'verified', 'rejected'])), name='ck_practitioner_credentials_status'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredential',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('issued_on__isnull', True), ('expires_on__gte', models.F('issued_on')), _connector='OR'), name='ck_practitioner_credentials_dates'),
        ),
        migrations.AddConstraint(
            model_name='practitionercredential',
            constraint=models.CheckConstraint(condition=models.Q(('issuing_country_code__isnull', True), ('issuing_country_code', django.db.models.functions.text.Upper('issuing_country_code')), _connector='OR'), name='ck_practitioner_credentials_country_upper'),
        ),
        migrations.AddIndex(
            model_name='practitionerfacilityassignment',
            index=models.Index(fields=['practitioner', 'is_active'], name='idx_prac_fac_asn_prac'),
        ),
        migrations.AddIndex(
            model_name='practitionerfacilityassignment',
            index=models.Index(fields=['facility', 'is_active'], name='idx_prac_fac_asn_fac'),
        ),
        migrations.AddConstraint(
            model_name='practitionerfacilityassignment',
            constraint=models.UniqueConstraint(fields=('practitioner', 'facility'), name='uq_practitioner_facility_assignments_pair'),
        ),
        migrations.AddConstraint(
            model_name='practitionerfacilityassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('practitioner',), name='uq_practitioner_primary_facility'),
        ),
        migrations.AddConstraint(
            model_name='practitionerfacilityassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='ck_practitioner_facility_assignments_dates'),
        ),
        migrations.AddConstraint(
            model_name='practitionerfacilityassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', False), ('is_active', True), _connector='OR'), name='ck_practitioner_facility_primary_active'),
        ),
        migrations.AddIndex(
            model_name='practitionerdepartmentassignment',
            index=models.Index(fields=['practitioner_facility_assignment', 'is_active'], name='idx_prac_dept_asn_pfa'),
        ),
        migrations.AddIndex(
            model_name='practitionerdepartmentassignment',
            index=models.Index(fields=['department'], name='idx_prac_dept_asn_dept'),
        ),
        migrations.AddConstraint(
            model_name='practitionerdepartmentassignment',
            constraint=models.UniqueConstraint(fields=('practitioner_facility_assignment', 'department'), name='uq_practitioner_department_assignments_pair'),
        ),
        migrations.AddConstraint(
            model_name='practitionerdepartmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('practitioner_facility_assignment',), name='uq_practitioner_primary_department'),
        ),
        migrations.AddConstraint(
            model_name='practitionerdepartmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='ck_practitioner_department_assignments_dates'),
        ),
        migrations.AddConstraint(
            model_name='practitionerdepartmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', False), ('is_active', True), _connector='OR'), name='ck_practitioner_department_primary_active'),
        ),
        migrations.AddIndex(
            model_name='practitionerspecialtyassignment',
            index=models.Index(fields=['practitioner_facility_assignment', 'is_active'], name='idx_prac_spec_asn_pfa'),
        ),
        migrations.AddIndex(
            model_name='practitionerspecialtyassignment',
            index=models.Index(fields=['facility_specialty'], name='idx_prac_spec_asn_spec'),
        ),
        migrations.AddConstraint(
            model_name='practitionerspecialtyassignment',
            constraint=models.UniqueConstraint(fields=('practitioner_facility_assignment', 'facility_specialty'), name='uq_practitioner_specialty_assignments_pair'),
        ),
        migrations.AddConstraint(
            model_name='practitionerspecialtyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('practitioner_facility_assignment',), name='uq_practitioner_primary_specialty'),
        ),
        migrations.AddConstraint(
            model_name='practitionerspecialtyassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='ck_practitioner_specialty_assignments_dates'),
        ),
        migrations.AddConstraint(
            model_name='practitionerspecialtyassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', False), ('is_active', True), _connector='OR'), name='ck_practitioner_specialty_primary_active'),
        ),
        migrations.AddConstraint(
            model_name='practitionertype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_practitioner_types_name'),
        ),
        migrations.AddConstraint(
            model_name='practitionertype',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_practitioner_types_code'),
        ),
        migrations.AddConstraint(
            model_name='practitionertype',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_practitioner_types_code_upper'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['organization'], name='idx_practitioners_organization'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['practitioner_type'], name='idx_practitioners_type'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='idx_practitioners_name'),
        ),
        migrations.AddConstraint(
            model_name='practitioner',
            constraint=models.UniqueConstraint(fields=('organization', 'practitioner_number'), name='uq_practitioners_org_number'),
        ),
        migrations.AddConstraint(
            model_name='practitioner',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('organization', 'user'), name='uq_practitioners_org_user'),
        ),
        migrations.AddConstraint(
            model_name='practitioner',
            constraint=models.CheckConstraint(condition=models.Q(('practitioner_number__regex', '.*\\S.*')), name='ck_practitioners_number_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='practitioner',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number__isnull', True), ('phone_number__regex', '^\\+[1-9][0-9]{7,14}$'), _connector='OR'), name='ck_practitioners_phone_e164'),
        ),
    ]
