# Generated by Django 5.2.4 on 2026-09-09 14:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0002_postgres_hardening'),
        ('facilities', '0002_postgres_hardening'),
        ('patients', '0001_initial'),
        ('practitioners', '0002_postgres_hardening'),
        ('scheduling', '0003_fix_practitioner_shift_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coding_system', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'diagnosis_codes',
                'indexes': [models.Index(fields=['coding_system', 'code'], name='idx_diagnosis_codes_lookup')],
                'constraints': [models.UniqueConstraint(fields=('coding_system', 'code'), name='uq_diagnosis_codes_system_code')],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter_number', models.CharField(max_length=50)),
                ('encounter_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('emergency', 'Emergency'), ('inpatient', 'Inpatient'), ('follow_up', 'Follow Up'), ('telemedicine', 'Telemedicine')], max_length=30)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('triage', 'Triage'), ('waiting_practitioner', 'Waiting Practitioner'), ('in_consultation', 'In Consultation'), ('awaiting_lab', 'Awaiting Lab'), ('awaiting_imaging', 'Awaiting Imaging'), ('awaiting_review', 'Awaiting Review'), ('awaiting_pharmacy', 'Awaiting Pharmacy'), ('awaiting_payment', 'Awaiting Payment'), ('admitted', 'Admitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='opened', max_length=30)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='scheduling.appointment')),
                ('attending_practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attending_encounters', to='practitioners.practitionerfacilityassignment')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_encounters', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_encounters', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='facilities.facility')),
                ('facility_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='facilities.facilityspecialty')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('patient_checkin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='checkins.patientcheckin')),
            ],
            options={
                'db_table': 'encounters',
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('consultation', 'Consultation'), ('progress', 'Progress'), ('review', 'Review'), ('specialist', 'Specialist'), ('discharge_note', 'Discharge Note'), ('addendum', 'Addendum')], max_length=30)),
                ('subjective_encrypted', models.TextField(blank=True, null=True)),
                ('objective_encrypted', models.TextField(blank=True, null=True)),
                ('assessment_encrypted', models.TextField(blank=True, null=True)),
                ('plan_encrypted', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='practitioners.practitionerfacilityassignment')),
                ('supersedes_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='clinical.clinicalnote')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='clinical.encounter')),
            ],
            options={
                'db_table': 'clinical_notes',
            },
        ),
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_text', models.CharField(max_length=250)),
                ('diagnosis_type', models.CharField(choices=[('provisional', 'Provisional'), ('differential', 'Differential'), ('confirmed', 'Confirmed')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes_encrypted', models.TextField(blank=True, null=True)),
                ('diagnosed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('diagnosed_by_practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter_diagnoses', to='practitioners.practitionerfacilityassignment')),
                ('diagnosis_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter_diagnoses', to='clinical.diagnosiscode')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='clinical.encounter')),
            ],
            options={
                'db_table': 'encounter_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='EncounterStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('opened', 'Opened'), ('triage', 'Triage'), ('waiting_practitioner', 'Waiting Practitioner'), ('in_consultation', 'In Consultation'), ('awaiting_lab', 'Awaiting Lab'), ('awaiting_imaging', 'Awaiting Imaging'), ('awaiting_review', 'Awaiting Review'), ('awaiting_pharmacy', 'Awaiting Pharmacy'), ('awaiting_payment', 'Awaiting Payment'), ('admitted', 'Admitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30, null=True)),
                ('to_status', models.CharField(choices=[('opened', 'Opened'), ('triage', 'Triage'), ('waiting_practitioner', 'Waiting Practitioner'), ('in_consultation', 'In Consultation'), ('awaiting_lab', 'Awaiting Lab'), ('awaiting_imaging', 'Awaiting Imaging'), ('awaiting_review', 'Awaiting Review'), ('awaiting_pharmacy', 'Awaiting Pharmacy'), ('awaiting_payment', 'Awaiting Payment'), ('admitted', 'Admitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('change_source', models.CharField(choices=[('system', 'System'), ('reception', 'Reception'), ('triage', 'Triage'), ('clinical', 'Clinical'), ('lab', 'Lab'), ('imaging', 'Imaging'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('admin', 'Admin')], default='system', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_encounter_statuses', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='clinical.encounter')),
            ],
            options={
                'db_table': 'encounter_status_history',
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triage_level', models.SmallIntegerField()),
                ('chief_complaint_encrypted', models.TextField(blank=True, null=True)),
                ('pain_score', models.SmallIntegerField(blank=True, null=True)),
                ('mobility_status', models.CharField(blank=True, max_length=30, null=True)),
                ('consciousness_level', models.CharField(blank=True, max_length=30, null=True)),
                ('notes_encrypted', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessments', to='clinical.encounter')),
                ('performed_by_practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_assessments', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'triage_assessments',
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('systolic_bp', models.SmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.SmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.SmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.SmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.SmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pain_score', models.SmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='clinical.encounter')),
                ('recorded_by_practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vital_signs', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'opened_at'], name='idx_encounters_patient_time'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility', 'status', 'opened_at'], name='idx_encounters_fac_status'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient_checkin'], name='idx_encounters_checkin'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(fields=('facility', 'encounter_number'), name='uq_encounters_facility_number'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['completed', 'cancelled']), _negated=True), fields=('patient_checkin',), name='uq_encounters_active_checkin'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('encounter_type__in', ['outpatient', 'emergency', 'inpatient', 'follow_up', 'telemedicine'])), name='ck_encounters_type'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['opened', 'triage', 'waiting_practitioner', 'in_consultation', 'awaiting_lab', 'awaiting_imaging', 'awaiting_review', 'awaiting_pharmacy', 'awaiting_payment', 'admitted', 'completed', 'cancelled'])), name='ck_encounters_status'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True), ('completed_by__isnull', True)), models.Q(('status', 'completed'), ('completed_at__isnull', False)), _connector='OR'), name='ck_encounters_completion'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('cancellation_reason__isnull', True)), models.Q(('status', 'cancelled'), ('cancelled_at__isnull', False), ('cancellation_reason__isnull', False)), _connector='OR'), name='ck_encounters_cancellation'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['encounter', 'created_at'], name='idx_clin_notes_enc_time'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnote',
            constraint=models.CheckConstraint(condition=models.Q(('note_type__in', ['consultation', 'progress', 'review', 'specialist', 'discharge_note', 'addendum'])), name='ck_clinical_notes_type'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnote',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes_note__isnull', True), models.Q(('supersedes_note', models.F('id')), _negated=True), _connector='OR'), name='ck_clinical_notes_supersede'),
        ),
        migrations.AddIndex(
            model_name='encounterdiagnosis',
            index=models.Index(fields=['encounter', 'diagnosed_at'], name='idx_enc_diag_enc_time'),
        ),
        migrations.AddConstraint(
            model_name='encounterdiagnosis',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('encounter',), name='uq_encounter_diagnoses_primary'),
        ),
        migrations.AddConstraint(
            model_name='encounterdiagnosis',
            constraint=models.CheckConstraint(condition=models.Q(('diagnosis_type__in', ['provisional', 'differential', 'confirmed'])), name='ck_encounter_diagnoses_type'),
        ),
        migrations.AddIndex(
            model_name='encounterstatushistory',
            index=models.Index(fields=['encounter', 'changed_at'], name='idx_enc_status_hist_time'),
        ),
        migrations.AddConstraint(
            model_name='encounterstatushistory',
            constraint=models.UniqueConstraint(condition=models.Q(('from_status__isnull', True)), fields=('encounter',), name='uq_encounter_status_history_initial'),
        ),
        migrations.AddConstraint(
            model_name='triageassessment',
            constraint=models.CheckConstraint(condition=models.Q(('triage_level__gte', 1), ('triage_level__lte', 4)), name='ck_triage_assessments_level'),
        ),
        migrations.AddConstraint(
            model_name='triageassessment',
            constraint=models.CheckConstraint(condition=models.Q(('pain_score__isnull', True), models.Q(('pain_score__gte', 0), ('pain_score__lte', 10)), _connector='OR'), name='ck_triage_assessments_pain'),
        ),
        migrations.AddConstraint(
            model_name='triageassessment',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='ck_triage_assessments_time'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['encounter', 'recorded_at'], name='idx_vital_signs_enc_time'),
        ),
    ]
