# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
        ('facilities', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_date', models.DateField()),
                ('next_sequence_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_queues', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_queues', to=settings.AUTH_USER_MODEL)),
                ('facility_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queues', to='facilities.facilityspecialty')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_queues', to=settings.AUTH_USER_MODEL)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queues', to='facilities.servicepoint')),
            ],
            options={
                'db_table': 'queues',
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.IntegerField()),
                ('priority_level', models.SmallIntegerField(default=0)),
                ('priority_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In Service'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], default='waiting', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('service_completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('patient_checkin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='checkins.patientcheckin')),
                ('practitioner_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='scheduling.practitionershift')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='queueing.queue')),
            ],
            options={
                'db_table': 'queue_entries',
            },
        ),
        migrations.CreateModel(
            name='QueueEntryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('joined', 'Joined'), ('called', 'Called'), ('recalled', 'Recalled'), ('skipped', 'Skipped'), ('service_started', 'Service Started'), ('service_completed', 'Service Completed'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred'), ('priority_changed', 'Priority Changed')], max_length=30)),
                ('from_status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In Service'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In Service'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry_events', to=settings.AUTH_USER_MODEL)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='queueing.queueentry')),
            ],
            options={
                'db_table': 'queue_entry_events',
            },
        ),
        migrations.CreateModel(
            name='QueueTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_reason', models.CharField(max_length=250)),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('destination_queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer', to='queueing.queueentry')),
                ('source_queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer', to='queueing.queueentry')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue_transfers',
            },
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['queue_date', 'status'], name='idx_queues_date_status'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['service_point', 'status'], name='idx_queue_sp_status'),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(condition=models.Q(('facility_specialty__isnull', True)), fields=('service_point', 'queue_date'), name='uq_queues_general'),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(condition=models.Q(('facility_specialty__isnull', False)), fields=('service_point', 'facility_specialty', 'queue_date'), name='uq_queues_specialty'),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.CheckConstraint(condition=models.Q(('next_sequence_number__gt', 0)), name='ck_queues_sequence'),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'open', 'paused', 'closed', 'cancelled'])), name='ck_queues_status'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['queue', 'status'], name='idx_queue_entries_queue_status'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['queue', '-priority_level', 'joined_at', 'sequence_number'], name='idx_queue_entries_order'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['patient_checkin'], name='idx_queue_entries_checkin'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['practitioner_shift'], name='idx_queue_entries_shift'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('queue', 'sequence_number'), name='uq_queue_entries_sequence'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('queue', 'patient_checkin'), name='uq_queue_entries_checkin'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_number__gt', 0)), name='ck_queue_entries_sequence'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('priority_level__gte', 0), ('priority_level__lte', 3)), name='ck_queue_entries_priority'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('priority_level', 0), ('priority_reason__isnull', False), _connector='OR'), name='ck_queue_entries_priority_reason'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['waiting', 'called', 'in_service', 'completed', 'skipped', 'cancelled', 'transferred'])), name='ck_queue_entries_status'),
        ),
        migrations.AddIndex(
            model_name='queueentryevent',
            index=models.Index(fields=['queue_entry', 'occurred_at'], name='idx_qentry_evt_entry_time'),
        ),
        migrations.AddIndex(
            model_name='queueentryevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='idx_qentry_evt_type_time'),
        ),
        migrations.AddConstraint(
            model_name='queueentryevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'joined')), fields=('queue_entry',), name='uq_queue_entry_events_one_joined'),
        ),
        migrations.AddConstraint(
            model_name='queueentryevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['joined', 'called', 'recalled', 'skipped', 'service_started', 'service_completed', 'cancelled', 'transferred', 'priority_changed'])), name='ck_queue_entry_events_type'),
        ),
        migrations.AddConstraint(
            model_name='queueentryevent',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__isnull', True), ('from_status__in', ['waiting', 'called', 'in_service', 'completed', 'skipped', 'cancelled', 'transferred']), _connector='OR'), name='ck_queue_entry_events_from_status'),
        ),
        migrations.AddConstraint(
            model_name='queueentryevent',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__isnull', True), ('to_status__in', ['waiting', 'called', 'in_service', 'completed', 'skipped', 'cancelled', 'transferred']), _connector='OR'), name='ck_queue_entry_events_to_status'),
        ),
        migrations.AddConstraint(
            model_name='queueentryevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['cancelled', 'transferred', 'priority_changed']), _negated=True), ('reason__isnull', False), _connector='OR'), name='ck_queue_entry_events_reason'),
        ),
        migrations.AddIndex(
            model_name='queuetransfer',
            index=models.Index(fields=['transferred_at'], name='idx_queue_transfers_time'),
        ),
        migrations.AddConstraint(
            model_name='queuetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_queue_entry', models.F('destination_queue_entry')), _negated=True), name='ck_queue_transfers_distinct'),
        ),
    ]
