# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('actual_started_at', models.DateTimeField(blank=True, null=True)),
                ('actual_ended_at', models.DateTimeField(blank=True, null=True)),
                ('accepts_appointments', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_practitioner_shifts', to=settings.AUTH_USER_MODEL)),
                ('consultation_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_shifts', to='facilities.consultationroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practitioner_shifts', to=settings.AUTH_USER_MODEL)),
                ('practitioner_department_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='practitioners.practitionerdepartmentassignment')),
                ('practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='practitioners.practitionerfacilityassignment')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_shifts', to='facilities.servicepoint')),
            ],
            options={
                'db_table': 'practitioner_shifts',
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.SmallIntegerField(default=1)),
                ('booked_count', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('is_online_bookable', models.BooleanField(default=True)),
                ('facility_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_slots', to='facilities.facilityspecialty')),
                ('practitioner_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_slots', to='scheduling.practitionershift')),
            ],
            options={
                'db_table': 'appointment_slots',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_number', models.CharField(max_length=50)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('queued', 'Queued'), ('in_service', 'In Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('booking_channel', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web'), ('reception', 'Reception'), ('api', 'API')], max_length=20)),
                ('reason_for_visit_encrypted', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.facility')),
                ('facility_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.facilityspecialty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('practitioner_facility_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='practitioners.practitionerfacilityassignment')),
                ('practitioner_specialty_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='practitioners.practitionerspecialtyassignment')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reschedules', to='scheduling.appointment')),
                ('appointment_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.appointmentslot')),
                ('practitioner_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.practitionershift')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('queued', 'Queued'), ('in_service', 'In Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('queued', 'Queued'), ('in_service', 'In Service'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], max_length=20)),
                ('change_source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('reception', 'Reception'), ('system', 'System'), ('api', 'API')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='scheduling.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_appointment_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_status_history',
                'indexes': [models.Index(fields=['appointment', 'changed_at'], name='idx_appt_hist_appt_time'), models.Index(fields=['to_status', 'changed_at'], name='idx_appt_hist_status_time')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('from_status__isnull', True)), fields=('appointment',), name='uq_appointment_history_one_initial'), models.CheckConstraint(condition=models.Q(('from_status__isnull', True), ('from_status__in', ['pending', 'confirmed', 'checked_in', 'queued', 'in_service', 'completed', 'cancelled', 'no_show', 'rescheduled']), _connector='OR'), name='ck_appointment_history_from_status'), models.CheckConstraint(condition=models.Q(('to_status__in', ['pending', 'confirmed', 'checked_in', 'queued', 'in_service', 'completed', 'cancelled', 'no_show', 'rescheduled'])), name='ck_appointment_history_to_status'), models.CheckConstraint(condition=models.Q(('change_source__in', ['web', 'mobile', 'reception', 'system', 'api'])), name='ck_appointment_history_source'), models.CheckConstraint(condition=models.Q(('from_status__isnull', True), models.Q(('from_status', models.F('to_status')), _negated=True), _connector='OR'), name='ck_appointment_history_change')],
            },
        ),
        migrations.CreateModel(
            name='PractitionerAvailabilityPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.SmallIntegerField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_available_for_appointments', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practitioner_availability_periods', to=settings.AUTH_USER_MODEL)),
                ('practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_periods', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'practitioner_availability_periods',
                'indexes': [models.Index(fields=['practitioner_facility_assignment', 'day_of_week', 'is_active'], name='idx_prac_avail_lookup'), models.Index(fields=['valid_from', 'valid_until'], name='idx_prac_avail_dates')],
                'constraints': [models.UniqueConstraint(fields=('practitioner_facility_assignment', 'day_of_week', 'starts_at', 'ends_at', 'valid_from'), name='uq_practitioner_availability_exact'), models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='ck_practitioner_availability_day'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_practitioner_availability_times'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='ck_practitioner_availability_dates')],
            },
        ),
        migrations.CreateModel(
            name='PractitionerLeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_practitioner_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_practitioner_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='practitioners.practitionerfacilityassignment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_practitioner_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practitioner_leave_requests',
                'indexes': [models.Index(fields=['practitioner_facility_assignment', 'status', 'starts_at', 'ends_at'], name='idx_practitioner_leave_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_practitioner_leave_times'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'cancelled'])), name='ck_practitioner_leave_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), ('decided_by__isnull', True), ('decided_at__isnull', True), ('cancelled_by__isnull', True), ('cancelled_at__isnull', True), ('cancellation_reason__isnull', True)), models.Q(('status__in', ['approved', 'rejected']), ('decided_by__isnull', False), ('decided_at__isnull', False), ('cancelled_by__isnull', True), ('cancelled_at__isnull', True), ('cancellation_reason__isnull', True)), models.Q(('status', 'cancelled'), ('cancelled_by__isnull', False), ('cancelled_at__isnull', False), ('cancellation_reason__isnull', False)), _connector='OR'), name='ck_practitioner_leave_state')],
            },
        ),
        migrations.AddIndex(
            model_name='practitionershift',
            index=models.Index(fields=['practitioner_facility_assignment', 'starts_at', 'ends_at'], name='idx_prac_shift_prac_time'),
        ),
        migrations.AddIndex(
            model_name='practitionershift',
            index=models.Index(fields=['practitioner_department_assignment'], name='idx_prac_shift_dept'),
        ),
        migrations.AddIndex(
            model_name='practitionershift',
            index=models.Index(fields=['service_point', 'starts_at', 'ends_at'], name='idx_prac_shift_sp_time'),
        ),
        migrations.AddIndex(
            model_name='practitionershift',
            index=models.Index(fields=['consultation_room', 'starts_at', 'ends_at'], name='idx_prac_shift_room_time'),
        ),
        migrations.AddIndex(
            model_name='practitionershift',
            index=models.Index(fields=['status'], name='idx_practitioner_shifts_status'),
        ),
        migrations.AddConstraint(
            model_name='practitionershift',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_practitioner_shifts_times'),
        ),
        migrations.AddConstraint(
            model_name='practitionershift',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['scheduled', 'in_progress', 'completed', 'cancelled'])), name='ck_practitioner_shifts_status'),
        ),
        migrations.AddConstraint(
            model_name='practitionershift',
            constraint=models.CheckConstraint(condition=models.Q(('actual_ended_at__isnull', True), models.Q(('actual_started_at__isnull', False), ('actual_ended_at__gt', models.F('actual_started_at'))), _connector='OR'), name='ck_practitioner_shifts_actual_times'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['practitioner_shift', 'starts_at'], name='idx_appt_slot_shift_time'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['facility_specialty', 'starts_at'], name='idx_appt_slot_spec_time'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(condition=models.Q(('is_online_bookable', True), ('status', 'available')), fields=['starts_at'], name='idx_appt_slot_avail'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.UniqueConstraint(fields=('practitioner_shift', 'facility_specialty', 'starts_at', 'ends_at'), name='uq_appointment_slots_exact'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_appointment_slots_times'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='ck_appointment_slots_capacity'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_count__gte', 0), ('booked_count__lte', models.F('capacity'))), name='ck_appointment_slots_booked_count'),
        ),
        migrations.AddConstraint(
            model_name='appointmentslot',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['available', 'full', 'blocked', 'cancelled'])), name='ck_appointment_slots_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['facility', 'scheduled_start'], name='idx_appointments_facility_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_start'], name='idx_appointments_patient_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['facility_specialty', 'scheduled_start'], name='idx_appt_spec_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['practitioner_facility_assignment', 'scheduled_start'], name='idx_appt_prac_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['practitioner_shift'], name='idx_appointments_shift'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_slot'], name='idx_appointments_slot'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_start'], name='idx_appointments_status_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['rescheduled_from'], name='idx_appt_resched_from'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('facility', 'appointment_number'), name='uq_appointments_facility_number'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='ck_appointments_times'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'checked_in', 'queued', 'in_service', 'completed', 'cancelled', 'no_show', 'rescheduled'])), name='ck_appointments_status'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('booking_channel__in', ['mobile', 'web', 'reception', 'api'])), name='ck_appointments_booking_channel'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('rescheduled_from__isnull', True), models.Q(('rescheduled_from', models.F('id')), _negated=True), _connector='OR'), name='ck_appointments_no_self_reschedule'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('cancellation_reason__isnull', False)), models.Q(('status__in', ['pending', 'confirmed', 'checked_in', 'queued', 'in_service', 'completed', 'no_show', 'rescheduled']), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('cancellation_reason__isnull', True)), _connector='OR'), name='ck_appointments_cancellation'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('practitioner_facility_assignment__isnull', True), ('practitioner_specialty_assignment__isnull', True), ('practitioner_shift__isnull', True), ('appointment_slot__isnull', True)), models.Q(('practitioner_facility_assignment__isnull', False), ('practitioner_specialty_assignment__isnull', False)), _connector='OR'), name='ck_appointments_practitioner_assignment_bundle'),
        ),
    ]
