# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queueing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueWaitTimePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('predicted_wait_minutes', models.IntegerField()),
                ('prediction_method', models.CharField(choices=[('rule_based', 'Rule Based'), ('machine_learning', 'Machine Learning')], max_length=30)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wait_time_predictions', to='queueing.queueentry')),
            ],
            options={
                'db_table': 'queue_wait_time_predictions',
                'indexes': [models.Index(fields=['queue_entry', '-generated_at'], name='idx_qwait_pred_entry_time'), models.Index(fields=['model_version', 'generated_at'], name='idx_qwait_pred_model_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('predicted_wait_minutes__gte', 0)), name='ck_queue_predictions_minutes'), models.CheckConstraint(condition=models.Q(('prediction_method__in', ['rule_based', 'machine_learning'])), name='ck_queue_predictions_method'), models.CheckConstraint(condition=models.Q(models.Q(('prediction_method', 'machine_learning'), _negated=True), ('model_version__isnull', False), _connector='OR'), name='ck_queue_predictions_model'), models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='ck_queue_predictions_confidence')],
            },
        ),
    ]
