# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_birth_is_estimated', models.BooleanField(default=False)),
                ('sex_code', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('intersex', 'Intersex'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164 format, for example +2557656765456.', regex='^\\+[1-9][0-9]{7,14}$')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='facilities.organization')),
                ('registered_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_patients', to='facilities.facility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['organization', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line1_encrypted', models.TextField(blank=True, null=True)),
                ('address_line2_encrypted', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_addresses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_addresses',
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifierType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_identifier_types', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_identifier_types', to='facilities.organization')),
            ],
            options={
                'db_table': 'patient_identifier_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value_encrypted', models.TextField()),
                ('value_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Hash values must be 64 hexadecimal characters.', regex='^[0-9A-Fa-f]{64}$')])),
                ('last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('issuing_country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=150, null=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_identifiers', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='patients.patient')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_patient_identifiers', to=settings.AUTH_USER_MODEL)),
                ('identifier_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_identifiers', to='patients.patientidentifiertype')),
            ],
            options={
                'db_table': 'patient_identifiers',
            },
        ),
        migrations.CreateModel(
            name='PatientRelatedPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('is_guardian', models.BooleanField(default=False)),
                ('is_caregiver', models.BooleanField(default=False)),
                ('is_next_of_kin', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('priority_order', models.SmallIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_related_persons', to=settings.AUTH_USER_MODEL)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_related_person_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_persons', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_related_persons',
            },
        ),
        migrations.CreateModel(
            name='PatientAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_access_grants', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_patient_access', to=settings.AUTH_USER_MODEL)),
                ('grantee_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_access_grants', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='patients.patient')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_patient_access', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_access_grants', to='accounts.role')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='patients.patientrelatedperson')),
            ],
            options={
                'db_table': 'patient_access_grants',
            },
        ),
        migrations.CreateModel(
            name='RelatedPersonContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('value_encrypted', models.TextField()),
                ('value_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Hash values must be 64 hexadecimal characters.', regex='^[0-9A-Fa-f]{64}$')])),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_related_person_contacts', to=settings.AUTH_USER_MODEL)),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='patients.patientrelatedperson')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_related_person_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'related_person_contacts',
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationship_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relationship_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='patientrelatedperson',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_related_persons', to='patients.relationshiptype'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization'], name='idx_patients_organization'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['registered_facility'], name='idx_patients_reg_fac'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='idx_patients_name'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('organization', 'patient_number'), name='uq_patients_org_number'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('organization', 'user'), name='uq_patients_org_user'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('patient_number__regex', '.*\\S.*')), name='ck_patients_number_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('sex_code__isnull', True), ('sex_code__in', ['male', 'female', 'intersex', 'unknown']), _connector='OR'), name='ck_patients_sex_code'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number__isnull', True), ('phone_number__regex', '^\\+[1-9][0-9]{7,14}$'), _connector='OR'), name='ck_patients_phone_e164'),
        ),
        migrations.AddIndex(
            model_name='patientaddress',
            index=models.Index(fields=['patient'], name='idx_patient_addresses_patient'),
        ),
        migrations.AddConstraint(
            model_name='patientaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('patient',), name='uq_patient_addresses_primary'),
        ),
        migrations.AddConstraint(
            model_name='patientaddress',
            constraint=models.CheckConstraint(condition=models.Q(('address_line1_encrypted__isnull', False), ('address_line2_encrypted__isnull', False), ('region__isnull', False), ('district__isnull', False), ('ward__isnull', False), ('postal_code__isnull', False), ('latitude__isnull', False), _connector='OR'), name='ck_patient_addresses_meaningful'),
        ),
        migrations.AddConstraint(
            model_name='patientaddress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='ck_patient_addresses_coordinates_pair'),
        ),
        migrations.AddConstraint(
            model_name='patientaddress',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='ck_patient_addresses_latitude'),
        ),
        migrations.AddConstraint(
            model_name='patientaddress',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='ck_patient_addresses_longitude'),
        ),
        migrations.AddConstraint(
            model_name='patientaddress',
            constraint=models.CheckConstraint(condition=models.Q(('country_code__isnull', True), ('country_code', django.db.models.functions.text.Upper('country_code')), _connector='OR'), name='ck_patient_addresses_country_upper'),
        ),
        migrations.AddIndex(
            model_name='patientidentifiertype',
            index=models.Index(fields=['organization'], name='idx_pat_id_type_org'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifiertype',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_patient_identifier_types_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifiertype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('organization__isnull', True)), name='uq_patient_identifier_types_global_name'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifiertype',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='uq_patient_identifier_types_global_code'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifiertype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), condition=models.Q(('organization__isnull', False)), name='uq_patient_identifier_types_org_name'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifiertype',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'code'), name='uq_patient_identifier_types_org_code'),
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(fields=['patient'], name='idx_pat_ident_patient'),
        ),
        migrations.AddIndex(
            model_name='patientidentifier',
            index=models.Index(fields=['identifier_type'], name='idx_patient_identifiers_type'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(fields=('identifier_type', 'value_hash'), name='uq_patient_identifiers_type_hash'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('patient', 'identifier_type'), name='uq_patient_identifiers_primary'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.CheckConstraint(condition=models.Q(('value_hash__regex', '^[0-9A-Fa-f]{64}$')), name='ck_patient_identifiers_hash'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('issued_on__isnull', True), ('expires_on__gte', models.F('issued_on')), _connector='OR'), name='ck_patient_identifiers_dates'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verified_at__isnull', True), ('verified_by__isnull', True)), models.Q(('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='ck_patient_identifiers_verification'),
        ),
        migrations.AddConstraint(
            model_name='patientidentifier',
            constraint=models.CheckConstraint(condition=models.Q(('issuing_country_code__isnull', True), ('issuing_country_code', django.db.models.functions.text.Upper('issuing_country_code')), _connector='OR'), name='ck_patient_identifiers_country_upper'),
        ),
        migrations.AddIndex(
            model_name='patientaccessgrant',
            index=models.Index(fields=['patient', 'is_active'], name='idx_pat_access_pat_act'),
        ),
        migrations.AddIndex(
            model_name='patientaccessgrant',
            index=models.Index(fields=['grantee_user', 'is_active'], name='idx_pat_access_grant_act'),
        ),
        migrations.AddIndex(
            model_name='patientaccessgrant',
            index=models.Index(fields=['role'], name='idx_patient_access_grants_role'),
        ),
        migrations.AddConstraint(
            model_name='patientaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('revoked_at__isnull', True)), fields=('patient', 'grantee_user', 'role'), name='uq_patient_access_grants_active'),
        ),
        migrations.AddConstraint(
            model_name='patientaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='ck_patient_access_grants_dates'),
        ),
        migrations.AddConstraint(
            model_name='patientaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('revocation_reason__isnull', True)), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('revocation_reason__isnull', False)), _connector='OR'), name='ck_patient_access_grants_revocation'),
        ),
        migrations.AddConstraint(
            model_name='patientaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('is_active', False), _connector='OR'), name='ck_patient_access_grants_revoked_inactive'),
        ),
        migrations.AddIndex(
            model_name='relatedpersoncontact',
            index=models.Index(fields=['related_person'], name='idx_rel_person_ctc'),
        ),
        migrations.AddConstraint(
            model_name='relatedpersoncontact',
            constraint=models.UniqueConstraint(fields=('related_person', 'channel', 'value_hash'), name='uq_related_person_contacts_value'),
        ),
        migrations.AddConstraint(
            model_name='relatedpersoncontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('related_person', 'channel'), name='uq_related_person_contacts_primary'),
        ),
        migrations.AddConstraint(
            model_name='relatedpersoncontact',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['phone', 'email'])), name='ck_related_person_contacts_channel'),
        ),
        migrations.AddConstraint(
            model_name='relatedpersoncontact',
            constraint=models.CheckConstraint(condition=models.Q(('value_hash__regex', '^[0-9A-Fa-f]{64}$')), name='ck_related_person_contacts_hash'),
        ),
        migrations.AddConstraint(
            model_name='relatedpersoncontact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verified_at__isnull', True), ('verified_by__isnull', True)), models.Q(('verified_at__isnull', False), ('verified_by__isnull', False)), _connector='OR'), name='ck_related_person_contacts_verification'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_relationship_types_name'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptype',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_relationship_types_code'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptype',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_relationship_types_code_upper'),
        ),
        migrations.AddIndex(
            model_name='patientrelatedperson',
            index=models.Index(fields=['patient'], name='idx_pat_rel_person_pat'),
        ),
        migrations.AddIndex(
            model_name='patientrelatedperson',
            index=models.Index(fields=['relationship_type'], name='idx_pat_rel_person_rel'),
        ),
        migrations.AddConstraint(
            model_name='patientrelatedperson',
            constraint=models.UniqueConstraint(condition=models.Q(('linked_user__isnull', False)), fields=('patient', 'linked_user'), name='uq_patient_related_persons_linked_user'),
        ),
        migrations.AddConstraint(
            model_name='patientrelatedperson',
            constraint=models.CheckConstraint(condition=models.Q(('priority_order__gt', 0)), name='ck_patient_related_persons_priority'),
        ),
    ]
