# Generated by Django 5.2.4 on 2026-09-09 14:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.CharField(max_length=150)),
                ('allergy_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reaction', models.CharField(blank=True, max_length=250, null=True)),
                ('severity', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved'), ('entered_in_error', 'Entered In Error')], default='active', max_length=30)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergies', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_patient_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_allergies',
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_pat_allergies_status'), models.Index(fields=['recorded_at'], name='idx_pat_allergies_time')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'resolved', 'entered_in_error'])), name='ck_patient_allergies_status'), models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('recorded_at')), _connector='OR'), name='ck_patient_allergies_resolution')],
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved'), ('entered_in_error', 'Entered In Error')], default='active', max_length=30)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes_encrypted', models.TextField(blank=True, null=True)),
                ('diagnosis_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_conditions', to='clinical.diagnosiscode')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_patient_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_conditions',
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_pat_conditions_status'), models.Index(fields=['diagnosis_code'], name='idx_pat_conditions_code')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'resolved', 'entered_in_error'])), name='ck_patient_conditions_status'), models.CheckConstraint(condition=models.Q(('resolved_date__isnull', True), ('onset_date__isnull', True), ('resolved_date__gte', models.F('onset_date')), _connector='OR'), name='ck_patient_conditions_dates')],
            },
        ),
    ]
