# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API'), ('system', 'System'), ('admin', 'Admin')], max_length=20)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='facilities.facility')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='facilities.organization')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='idx_audit_logs_org_time'), models.Index(fields=['facility', '-occurred_at'], name='idx_audit_logs_facility_time'), models.Index(fields=['actor_user', '-occurred_at'], name='idx_audit_logs_actor_time'), models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='idx_audit_logs_entity'), models.Index(condition=models.Q(('request_id__isnull', False)), fields=['request_id'], name='idx_audit_logs_request')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source__in', ['web', 'mobile', 'api', 'system', 'admin'])), name='ck_audit_logs_source'), models.CheckConstraint(condition=models.Q(('action__regex', '.*\\S.*')), name='ck_audit_logs_action_not_blank'), models.CheckConstraint(condition=models.Q(('entity_type__regex', '.*\\S.*')), name='ck_audit_logs_entity_type_not_blank')],
            },
        ),
    ]
