# Generated by Django 5.2.4 on 2026-09-09 19:05

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('facilities', '0002_postgres_hardening'),
        ('practitioners', '0002_postgres_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('strength', models.CharField(blank=True, max_length=80, null=True)),
                ('strength_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=80, null=True)),
                ('route_default', models.CharField(blank=True, max_length=80, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='facilities.organization')),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('prescribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical.encounter')),
                ('prescribed_by_practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='practitioners.practitionerfacilityassignment')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('route', models.CharField(blank=True, max_length=80, null=True)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_value', models.IntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity_prescribed', models.DecimalField(decimal_places=3, max_digits=12)),
                ('instructions_encrypted', models.TextField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='MedicationDispense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_batch_id', models.UUIDField(blank=True, null=True)),
                ('quantity_dispensed', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='dispensed', max_length=30)),
                ('notes_encrypted', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dispensed_by_practitioner_facility_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_dispenses', to='practitioners.practitionerfacilityassignment')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.prescriptionitem')),
            ],
            options={
                'db_table': 'medication_dispenses',
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['organization', 'is_active'], name='idx_medications_org_active'),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_medications_org_code'),
        ),
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='ck_medications_code_upper'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['encounter', 'prescribed_at'], name='idx_prescriptions_enc_time'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'partially_dispensed', 'dispensed', 'cancelled'])), name='ck_prescriptions_status'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('cancellation_reason__isnull', True)), models.Q(('status', 'cancelled'), ('cancelled_at__isnull', False), ('cancellation_reason__isnull', False)), _connector='OR'), name='ck_prescriptions_cancellation'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription'], name='idx_prescription_items_rx'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('dose__isnull', True), ('dose__gt', 0), _connector='OR'), name='ck_prescription_items_dose'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('duration_value__isnull', True), ('duration_value__gt', 0), _connector='OR'), name='ck_prescription_items_duration'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_prescribed__gt', 0)), name='ck_prescription_items_quantity'),
        ),
        migrations.AddIndex(
            model_name='medicationdispense',
            index=models.Index(fields=['prescription_item'], name='idx_medication_dispenses_item'),
        ),
        migrations.AddConstraint(
            model_name='medicationdispense',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_dispensed__gt', 0)), name='ck_medication_dispenses_quantity'),
        ),
        migrations.AddConstraint(
            model_name='medicationdispense',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'partially_dispensed', 'dispensed', 'cancelled'])), name='ck_medication_dispenses_status'),
        ),
    ]
