# Generated by Django 5.2.4 on 2026-07-08 20:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('queueing', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('appointment_confirmation', 'Appointment Confirmation'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_cancelled', 'Appointment Cancelled'), ('queue_joined', 'Queue Joined'), ('queue_updated', 'Queue Updated'), ('queue_called', 'Queue Called'), ('general', 'General')], max_length=40)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('in_app', 'In App')], max_length=20)),
                ('destination_encrypted', models.TextField(blank=True, null=True)),
                ('subject_encrypted', models.TextField(blank=True, null=True)),
                ('body_encrypted', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attempt_count', models.SmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=150, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='scheduling.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_notifications', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='patients.patient')),
                ('queue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='queueing.queueentry')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_notifications',
                'indexes': [models.Index(condition=models.Q(('status__in', ['pending', 'processing'])), fields=['status', 'scheduled_for'], name='idx_pat_notif_dispatch'), models.Index(fields=['patient', '-created_at'], name='idx_pat_notif_pat_time'), models.Index(fields=['appointment'], name='idx_pat_notif_appt'), models.Index(fields=['queue_entry'], name='idx_pat_notif_queue'), models.Index(fields=['recipient_user'], name='idx_pat_notif_recip')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uq_patient_notifications_idempotency'), models.CheckConstraint(condition=models.Q(('notification_type__in', ['appointment_confirmation', 'appointment_reminder', 'appointment_rescheduled', 'appointment_cancelled', 'queue_joined', 'queue_updated', 'queue_called', 'general'])), name='ck_patient_notifications_type'), models.CheckConstraint(condition=models.Q(('channel__in', ['sms', 'email', 'push', 'in_app'])), name='ck_patient_notifications_channel'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'sent', 'delivered', 'failed', 'cancelled'])), name='ck_patient_notifications_status'), models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='ck_patient_notifications_attempts'), models.CheckConstraint(condition=models.Q(('channel', 'in_app'), ('destination_encrypted__isnull', False), _connector='OR'), name='ck_patient_notifications_destination'), models.CheckConstraint(condition=models.Q(models.Q(('channel__in', ['push', 'in_app']), _negated=True), ('recipient_user__isnull', False), _connector='OR'), name='ck_patient_notifications_recipient'), models.CheckConstraint(condition=models.Q(('appointment__isnull', False), ('queue_entry__isnull', False), _negated=True), name='ck_patient_notifications_single_source'), models.CheckConstraint(condition=models.Q(('delivered_at__isnull', False), ('failed_at__isnull', False), _negated=True), name='ck_patient_notifications_outcome')],
            },
        ),
        migrations.CreateModel(
            name='UserPushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=15)),
                ('token_encrypted', models.TextField()),
                ('token_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Hash values must be 64 hexadecimal characters.', regex='^[0-9A-Fa-f]{64}$')])),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=30, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_push_devices',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_push_dev_user_act')],
                'constraints': [models.UniqueConstraint(fields=('token_hash',), name='uq_user_push_devices_hash'), models.CheckConstraint(condition=models.Q(('platform__in', ['android', 'ios', 'web'])), name='ck_user_push_devices_platform'), models.CheckConstraint(condition=models.Q(('token_hash__regex', '^[0-9A-Fa-f]{64}$')), name='ck_user_push_devices_hash'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('is_active', False), _connector='OR'), name='ck_user_push_devices_revocation')],
            },
        ),
    ]
